# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 608)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/Downloads/python/back1.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkin_label = QtWidgets.QLabel(self.centralwidget)
        self.checkin_label.setGeometry(QtCore.QRect(180, 40, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.checkin_label.setFont(font)
        self.checkin_label.setObjectName("checkin_label")
        self.area_maps = QtWidgets.QScrollArea(self.centralwidget)
        self.area_maps.setGeometry(QtCore.QRect(170, 210, 201, 141))
        self.area_maps.setWidgetResizable(True)
        self.area_maps.setObjectName("area_maps")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 199, 139))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.area_maps.setWidget(self.scrollAreaWidgetContents)
        self.navigator_label = QtWidgets.QLabel(self.centralwidget)
        self.navigator_label.setGeometry(QtCore.QRect(220, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.navigator_label.setFont(font)
        self.navigator_label.setObjectName("navigator_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 410, 270, 38))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.problembutton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.problembutton.setFont(font)
        self.problembutton.setObjectName("problembutton")
        self.gridLayout.addWidget(self.problembutton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.arrivedbutton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.arrivedbutton.setFont(font)
        self.arrivedbutton.setObjectName("arrivedbutton")
        self.gridLayout.addWidget(self.arrivedbutton, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkin_label.setText(_translate("MainWindow", "CHECK-IN"))
        self.navigator_label.setText(_translate("MainWindow", "Navigator"))
        self.problembutton.setText(_translate("MainWindow", "Problem"))
        self.arrivedbutton.setText(_translate("MainWindow", "Arrivred"))
import test12_rc
